### ISSUE TITLE
Facing issue in running corteza example from this documentation on local environment ( Mac os )

### ISSUE THREAD

**Issue by Sharvin26** [cortezaproject/corteza-docs#2]
Hello

I am trying to run the corteza example provided here https://github.com/cortezaproject/corteza-docs/blob/master/deploy/docker-compose/example-2019-07-os.com/docker-compose.yml on my local machine.

#### Configuration =>

1. Mac OS
2. Docker version
```➜ docker -v
Docker version 19.03.1, build 74b1e89
```
3. Docker-compose version
```
➜ docker-compose -v
docker-compose version 1.24.1, build 4667896b
```
4. Docker compose file =>

```
version: '2.0'

services:
  db:
    image: percona:8.0
    environment:
      MYSQL_DATABASE:      corteza
      MYSQL_USER:          corteza
      MYSQL_PASSWORD:      oscom-tutorial
      MYSQL_ROOT_PASSWORD: supertopsecret

  server:
    image: cortezaproject/corteza-server:latest

    # Map internal 80 port (where Corteza API is listening)
    # to external port 10080. If you change this, make sure you change API_BASEURL setting below
    ports: [ "10080:80" ]

    environment:
      # Tell corteza-server where can it be reached from the outside
      VIRTUAL_HOST: localhost:10080

      # Serving the app from the localhost port 20080 is not very usual setup,
      # this will override settings auto-discovery procedure (provision) and
      # use custom values for frontend URL base
      PROVISION_SETTINGS_AUTH_FRONTEND_URL_BASE: http://localhost:20080

      # Database connection, make sure username, password, and database matches values in the db service
      DB_DSN: corteza:oscom-tutorial@tcp(db:3306)/corteza?collation=utf8mb4_general_ci

  webapp:
    image: cortezaproject/corteza-webapp:latest

    # Map internal 80 port (where we serve the web application)
    # to external port 20080.
    ports: [ "20080:80" ]

    environment:
      # Where API can be found
      API_BASEURL: localhost:10080

      # We're using one service for the API
      MONOLITH_API: 1
```
5. .env file =>

```
# You can use project name variable to prefix all containers with something useful
# We suggesst you use your domain name (and substitute dots with dashes)
#COMPOSE_PROJECT_NAME=corteza

# We'll use this in all variables in docker-compose.yml
DOMAIN=local.cortezaproject.org

AUTH_JWT_SECRET=MaZkTdp2E9wbUEs7Ninu


# Version of Corteza Docker images
VERSION=latest

# Secret to use for JWT token
# Uncomment and set it to some random string (30 char should be enough)
# (if not set, JWT secret will be regenerated each time you restart the
#  backend server causing users to re-login)
#AUTH_JWT_SECRET=

# SMTP settings
# Point this to your local or external SMTP server
#SMTP_HOST=
#SMTP_USER=
#SMTP_PASS=
SMTP_FROM="Corteza" <info@local.cortezaproject.org>

DB_DSN=corteza:change-me@tcp(db:3306)/corteza?collation=utf8mb4_general_ci
```

7. Nginx compose file =>

```
version: '3.5'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/htpasswd:/etc/nginx/htpasswd
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
#      - ./conf.d/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-letsencrypt:
    depends_on:
      - nginx-proxy
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

# Create network if it does not exist
networks: { proxy: { name: proxy } }
```

### Running the docker-compose

```
➜ docker-compose up

Starting corteza_server_1 ... done
Starting corteza_webapp_1 ... done
Starting corteza_db_1     ... done
```

#### Intial Logs =>

```
Attaching to corteza_server_1, corteza_db_1, corteza_webapp_1
server_1  | {"level":"warn","ts":1565260672.244429,"logger":"compose.database","caller":"db/connector.go:59","msg":"could not connect to the database","name":"compose","error":"dial tcp 172.19.0.3:3306: connect: connection refused","try":1,"dsn":"c****a:o****l@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
db_1      | 2019-08-08T10:37:52.619091Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.15-6) starting as process 1
db_1      | 2019-08-08T10:37:53.013299Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1      | 2019-08-08T10:37:53.036018Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.15-6'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  Percona Server (GPL), Release 6, Revision 63abd08.
db_1      | 2019-08-08T10:37:53.173774Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/lib/mysql/mysqlx.sock' bind-address: '::' port: 33060
server_1  | {"level":"info","ts":1565260677.2546263,"logger":"compose.database","caller":"db/connector.go:77","msg":"connected to the database","name":"compose","dsn":"c****a:o****l@tcp(db:3306)/corteza?collation=utf8mb4_general_ci"}
server_1  | {"level":"info","ts":1565260677.2596135,"logger":"messaging.database","caller":"db/connector.go:77","msg":"connected to the database","name":"messaging","dsn":"c****a:o****l@tcp(db:3306)/corteza?collation=utf8mb4_general_ci"}
server_1  | {"level":"info","ts":1565260677.2630515,"logger":"system.database","caller":"db/connector.go:77","msg":"connected to the database","name":"system","dsn":"c****a:o****l@tcp(db:3306)/corteza?collation=utf8mb4_general_ci"}
server_1  | {"level":"info","ts":1565260677.2878294,"logger":"compose","caller":"service/service.go:42","msg":"initializing store","path":"/data/compose"}
server_1  | {"level":"info","ts":1565260677.3025148,"logger":"messaging","caller":"service/service.go:45","msg":"initializing store","path":"/data/messaging"}
server_1  | {"level":"info","ts":1565260677.3296645,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.external.enabled","value":""}
server_1  | {"level":"info","ts":1565260677.3301568,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.external.redirect-url","value":"https://localhost:10080/system/auth/external/%s/callback"}
server_1  | {"level":"info","ts":1565260677.3307388,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.external.session-store-secret","value":"2rNCabfDezyklHnS6d7mOk6RoJhznjJe4MlbCtyn0V7OHVX1i1y0i1mB6RJy1Az1"}
server_1  | {"level":"info","ts":1565260677.3308818,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.external.session-store-secure","value":""}
server_1  | {"level":"info","ts":1565260677.3314402,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.frontend.url.base","value":"http://localhost:20080"}
server_1  | {"level":"info","ts":1565260677.331852,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.frontend.url.password-reset","value":"http://localhost:20080/auth/reset-password?token="}
server_1  | {"level":"info","ts":1565260677.3319602,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.frontend.url.email-confirmation","value":"http://localhost:20080/auth/confirm-email?token="}
server_1  | {"level":"info","ts":1565260677.3322816,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.frontend.url.redirect","value":"http://localhost:20080/auth"}
server_1  | {"level":"info","ts":1565260677.3323958,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.mail.from-address","value":"to-be-configured@example.tld"}
server_1  | {"level":"info","ts":1565260677.3324523,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.mail.from-name","value":"Corteza Team (to-be-configured)"}
server_1  | {"level":"info","ts":1565260677.3328598,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.internal.enabled","value":""}
server_1  | {"level":"info","ts":1565260677.3329213,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.internal.signup.enabled","value":""}
server_1  | {"level":"info","ts":1565260677.333383,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.internal.signup-email-confirmation-required","value":""}
server_1  | {"level":"info","ts":1565260677.3335443,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:54","msg":"already set","name":"auth.internal.password-reset.enabled","value":""}
server_1  | {"level":"info","ts":1565260677.3365762,"logger":"http","caller":"api/server.go:82","msg":"Starting HTTP server with REST API","address":":80"}

```

#### Problem =>

Now when I open the browser ( **Note:** I am using Google Chrome ) using the following url 
http://localhost:20080 it redirects to this url http://localhost/auth/ and I get the error =>

 ```
503 Service Temporarily Unavailable
nginx/1.14.1
```

##### Logs =>

```
webapp_1  | {"@timestamp":"2019-08-08T10:42:04+00:00","remote_addr":"172.19.0.1","request":"GET /config.js HTTP/1.1","status":304,"body_bytes_sent":0,"request_time":0.000,"http_referrer":"http://localhost:20080/","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
```
##### Ngnix Logs =>

```
nginx.1    | localhost 172.20.0.1 - - [08/Aug/2019:11:01:38 +0000] "GET /auth/ HTTP/1.1" 503 615 "http://localhost:20080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
nginx.1    | localhost 172.20.0.1 - - [08/Aug/2019:11:01:38 +0000] "GET /favicon.ico HTTP/1.1" 503 615 "http://localhost/auth/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

```
What am I doing wrong here?
